# Generated by Django 4.2.6 on 2023-10-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='depth',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
